global_props:
  rand_seed: 10

logging:
  # file: logs/log
  dir: logs/exp
  level: info

dump:
  user: pavel
  title: exp_3

models:
  lorenz:
    rand_seed: 10
    dt: 0.001
    ro: 80

schemes:
  hyper_param:
    evaluate:
      n: 15000
      split_n: 10000
      normalize: true
      model: lorenz
      metric: mse
    esn:
      n_reservoir: 600
      random_state: 3
      in_activation: tanh
      out_activation: identity
    evo:
      dump_dir: dumps/exp

      rand_seed: 5
      max_gen_num: 40
      population_size: 128
      hall_of_fame: 8
      hromo_len: 6
      # mandatory_new_num: 16

      verbose: true

      fitness_weights: [ -1.0 ]

      select:
        method: selTournament
        args:
          - key: tournsize
            val: 2
      mate:
        method: dynoCxGeneByLimit
        probability: 0.85
      mutate:
        method: dynoMutGeneByLimit
        probability: 0.25
        # indpb: 0.5
      limits:
        # spectral_radius
        - type: float
          min: 1.e-8
          max: 2
          mate:
            method: cxGaussianBoundedGene
            args:
              - key: up
                val: 2
              - key: low
                val: 1.e-4
              - key: eta
                val: 10
          mutate:
            method: polynomialBounded
            args:
              - key: up
                val: 2
              - key: low
                val: 1.e-4
              - key: eta
                val: 10
        # sparsity
        - type: float
          min: 1.e-4
          max: 1.
          mate:
            method: cxGaussianBoundedGene
            args:
              - key: up
                val: 1.
              - key: low
                val: 1.e-4
              - key: eta
                val: 10
          mutate:
            method: polynomialBounded
            args:
              - key: up
                val: 1.
              - key: low
                val: 1.e-8
              - key: eta
                val: 10
        # lambda_r
        - type: float
          min: 1.e-12
          max: 1.
          mate:
            method: cxGaussianBoundedGene
            args:
              - key: up
                val: 1.
              - key: low
                val: 1.e-12
              - key: eta
                val: 10
          mutate:
            method: polynomialBounded
            args:
              - key: up
                val: 1.
              - key: low
                val: 1.e-12
              - key: eta
                val: 10
        # regulirization
        - type: choice
          choice: ['noise', 'l2', null]
          mate:
            method: cxRandChoiceGene
        # use_bias
        - type: bool
          mate:
            method: cxRandChoiceGene
        # use_additive_noise_when_forecasting
        - type: bool
          mate:
            method: cxRandChoiceGene

      metrics:
        - name: max
          func: max
          package: numpy
        - name: avg
          func: mean
          package: numpy
